import { test, expect } from '@playwright/test';

test('salesforce', async ({ page, context, browser }) => {
  // Test Steps
  await page.goto('https://farmers.okta.com/oauth2/v1/authorize?client_id=okta.2b1959c8-bcc0-56eb-a589-cfcfb7422f26&code_challenge=ISMPfb7Bnnk7YcPj39gcATsoNXOozPkAoV3BuG9ndjE&code_challenge_method=S256&nonce=fQb3ltjwNOCeGX4srzCUOjRWqRYQFbphiFeC7MYUiaaivARvtbiUPGrnL34d0Jai&redirect_uri=https%3A%2F%2Ffarmers.okta.com%2Fenduser%2Fcallback&response_type=code&state=KbuliJucAeAvCHVyzF1lr689Bp05uzaKDYGtEaqobWsDcZ5BhUS4DFEegsiQX1tZ&scope=openid%20profile%20email%20okta.users.read.self%20okta.users.manage.self%20okta.internal.enduser.read%20okta.internal.enduser.manage%20okta.enduser.dashboard.read%20okta.enduser.dashboard.manage%20okta.myAccount.sessions.manage%20okta.internal.navigation.enduser.read');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-1.png', fullPage: false });
  const _loc2 = await page.locator('role=textbox[name="myID or Username"]');
  await _loc2.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc2.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-2.png', fullPage: false });
  await _loc2.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc2.click();
  const _loc3 = await page.locator('role=textbox[name="myID or Username"]');
  await _loc3.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc3.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-3.png', fullPage: false });
  await _loc3.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc3.fill('browbck_td');
  const _loc4 = await page.locator('role=button[name="Next"]');
  await _loc4.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc4.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-4.png', fullPage: false });
  await _loc4.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc4.click();
  const _loc5 = await page.locator('role=textbox[name="Password"]');
  await _loc5.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc5.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-5.png', fullPage: false });
  await _loc5.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc5.click();
  const _loc6 = await page.locator('role=textbox[name="Password"]');
  await _loc6.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc6.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-6.png', fullPage: false });
  await _loc6.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc6.fill('Welcome@123Welcome@123');
  await page.locator('role=textbox[name="Password"]').dblclick();
  const _loc7 = await page.locator('role=textbox[name="Password"]');
  await _loc7.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc7.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-7.png', fullPage: false });
  await _loc7.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc7.fill('Welcome@123');
  const _loc8 = await page.locator('role=button[name="Verify"]');
  await _loc8.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc8.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-8.png', fullPage: false });
  await _loc8.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc8.click();
  const _loc9 = await page.locator('role=link[name="launch app APEX UAT"]');
  await _loc9.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc9.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-9.png', fullPage: false });
  await _loc9.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc9.click();
  const _loc10 = await page.locator('role=link[name="Accounts"]');
  await _loc10.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc10.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-10.png', fullPage: false });
  await _loc10.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc10.click();
  const _loc11 = await page.locator('role=button[name="New"]');
  await _loc11.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc11.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-11.png', fullPage: false });
  await _loc11.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc11.click();
  const _loc12 = await page.locator('.slds-radio--faux');
  await _loc12.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc12.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-12.png', fullPage: false });
  await _loc12.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc12.click();
  const _loc13 = await page.locator('role=button[name="Next"]');
  await _loc13.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc13.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-13.png', fullPage: false });
  await _loc13.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc13.click();
  const _loc14 = await page.locator('role=combobox[name="Salutation"]');
  await _loc14.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc14.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-14.png', fullPage: false });
  await _loc14.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc14.click();
  const _loc15 = await page.locator('span');
  await _loc15.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc15.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-15.png', fullPage: false });
  await _loc15.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc15.click();
  const _loc16 = await page.locator('role=textbox[name="First Name"]');
  await _loc16.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc16.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-16.png', fullPage: false });
  await _loc16.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc16.click();
  const _loc17 = await page.locator('role=textbox[name="First Name"]');
  await _loc17.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc17.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-17.png', fullPage: false });
  await _loc17.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc17.fill('Mike');
  const _loc18 = await page.locator('role=textbox[name="Last Name"]');
  await _loc18.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc18.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-18.png', fullPage: false });
  await _loc18.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc18.click();
  const _loc19 = await page.locator('role=textbox[name="Last Name"]');
  await _loc19.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc19.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-19.png', fullPage: false });
  await _loc19.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc19.fill('R');
  const _loc20 = await page.locator('role=combobox[name="Source Category (PL)"]');
  await _loc20.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc20.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-20.png', fullPage: false });
  await _loc20.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc20.click();
  const _loc21 = await page.locator('role=option[name="Direct Contact"]');
  await _loc21.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc21.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-21.png', fullPage: false });
  await _loc21.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc21.click();
  const _loc22 = await page.locator('role=combobox[name="Current Lead Source (PL)"]');
  await _loc22.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc22.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-22.png', fullPage: false });
  await _loc22.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc22.click();
  const _loc23 = await page.locator('span');
  await _loc23.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc23.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-23.png', fullPage: false });
  await _loc23.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc23.click();
  const _loc24 = await page.locator('role=combobox[name="Residence Country"]');
  await _loc24.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc24.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-24.png', fullPage: false });
  await _loc24.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc24.click();
  const _loc25 = await page.locator('text=United States');
  await _loc25.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc25.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-25.png', fullPage: false });
  await _loc25.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc25.click();
  const _loc26 = await page.locator('role=combobox[name="Address Search"]');
  await _loc26.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc26.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-26.png', fullPage: false });
  await _loc26.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc26.click();
  const _loc27 = await page.locator('role=combobox[name="Address Search"]');
  await _loc27.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc27.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-27.png', fullPage: false });
  await _loc27.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc27.click();
  const _loc28 = await page.locator('role=combobox[name="Address Search"]');
  await _loc28.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc28.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-28.png', fullPage: false });
  await _loc28.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc28.fill('1');
  const _loc29 = await page.locator('role=option[name="1100 Van Ness Avenue San"]');
  await _loc29.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc29.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-29.png', fullPage: false });
  await _loc29.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc29.click();
  const _loc30 = await page.locator('role=button[name="Save"]');
  await _loc30.evaluate(el => el.style.outline = '4px solid #ef4444');
  await _loc30.evaluate(el => el.style.outlineOffset = '2px');
  await page.screenshot({ path: '/Users/mikeroy/Downloads/Telegram Desktop/playwright-web-app/agent/storage/e3157e0d-8a52-4e35-88fd-0385169ad962/screenshots/step-30.png', fullPage: false });
  await _loc30.evaluate(el => { el.style.outline = ''; el.style.outlineOffset = ''; });
  await _loc30.click();
});
