export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Premium Dark Theme (Zinc-based)
        dark: {
          bg: 'var(--bg-primary)',
          card: 'var(--bg-secondary)',
          elevated: 'var(--bg-elevated)',
          canvas: 'var(--bg-canvas)',
          overlay: 'var(--bg-overlay)',
          shell: 'var(--bg-shell)',
        },
        brand: {
          primary: 'var(--brand-primary)',
          secondary: 'var(--brand-secondary)',
          'primary-depth': 'var(--brand-primary-depth)',
          hover: 'var(--brand-hover)',
        },
        border: {
          default: 'var(--border-default)',
          muted: 'var(--border-subtle)',
          emphasis: 'var(--border-emphasis)',
          active: 'var(--border-active)',
          selected: 'var(--border-selected)',
          disabled: 'var(--border-disabled)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverted: 'var(--text-inverted)',
          disabled: 'var(--text-disabled)',
          'on-selected': 'var(--text-on-selected)',
          link: 'var(--text-link)',
        },
        status: {
          success: 'var(--status-success)',
          warning: 'var(--status-warning)',
          danger: 'var(--status-danger)',
          info: 'var(--status-info)',
        },
        accent: {
          blue: 'var(--brand-primary)',
          purple: 'var(--accent-purple)',
          teal: 'var(--accent-teal)',
          orange: 'var(--accent-orange)',
        },
        surface: {
          selected: 'var(--bg-selected)',
          'selected-muted': 'var(--bg-selected-muted)',
          hover: 'var(--bg-hover)',
          disabled: 'var(--bg-disabled)',
          danger: 'var(--bg-danger-surface)',
          info: 'var(--bg-info-surface)',
        },
        badge: {
          'running-bg': 'var(--badge-running-bg)',
          'running-text': 'var(--badge-running-text)',
          'running-border': 'var(--badge-running-border)',
          'queued-bg': 'var(--badge-queued-bg)',
          'queued-text': 'var(--badge-queued-text)',
          'queued-border': 'var(--badge-queued-border)',
          'canceled-bg': 'var(--badge-canceled-bg)',
          'canceled-text': 'var(--badge-canceled-text)',
          'canceled-border': 'var(--badge-canceled-border)',
          'error-bg': 'var(--badge-error-bg)',
          'error-text': 'var(--badge-error-text)',
          'error-border': 'var(--badge-error-border)',
          'passed-bg': 'var(--badge-passed-bg)',
          'passed-text': 'var(--badge-passed-text)',
          'passed-border': 'var(--badge-passed-border)',
          'unstable-bg': 'var(--badge-unstable-bg)',
          'unstable-text': 'var(--badge-unstable-text)',
          'unstable-border': 'var(--badge-unstable-border)',
          'neutral-bg': 'var(--badge-neutral-bg)',
          'neutral-text': 'var(--badge-neutral-text)',
          'neutral-border': 'var(--badge-neutral-border)',
        },
        dot: {
          passed: 'var(--dot-passed)',
          failed: 'var(--dot-failed)',
          running: 'var(--dot-running)',
          pending: 'var(--dot-pending)',
          muted: 'var(--dot-muted)',
        },
        danger: {
          surface: 'var(--bg-danger-surface)',
          border: 'var(--border-danger-emphasis)',
          bright: 'var(--text-danger-bright)',
          label: 'var(--text-danger-label)',
        },
        info: {
          surface: 'var(--bg-info-surface)',
          border: 'var(--border-info-emphasis)',
          bright: 'var(--text-info-bright)',
        },
        'accent-purple': {
          bg: 'var(--accent-purple-bg)',
          'bg-hover': 'var(--accent-purple-bg-hover)',
          border: 'var(--accent-purple-border)',
          text: 'var(--accent-purple-text)',
        },
        shard: {
          1:  'var(--shard-1)',
          2:  'var(--shard-2)',
          3:  'var(--shard-3)',
          4:  'var(--shard-4)',
          5:  'var(--shard-5)',
          6:  'var(--shard-6)',
          7:  'var(--shard-7)',
          8:  'var(--shard-8)',
          9:  'var(--shard-9)',
          10: 'var(--shard-10)',
          11: 'var(--shard-11)',
          12: 'var(--shard-12)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        '4xs': ['9px', { lineHeight: '12px', letterSpacing: '0.04em' }],
        '3xs': ['10px', { lineHeight: '14px', letterSpacing: '0.03em' }],
        'xxs': ['11px', { lineHeight: '14px', letterSpacing: '0.02em' }],
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['13px', { lineHeight: '20px' }],
        'base': ['14px', { lineHeight: '24px' }],
        'lg': ['16px', { lineHeight: '24px' }],
        'xl': ['18px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
      },
      borderRadius: {
        'sm': '2px',
        'DEFAULT': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
      },
      boxShadow: {
        'none': 'none',
        'sm': '0 1px 2px rgba(0, 0, 0, 0.2)',
        'md': '0 2px 4px rgba(0, 0, 0, 0.25)',
        'lg': '0 4px 8px rgba(0, 0, 0, 0.3)',
        'xl': '0 8px 16px rgba(0, 0, 0, 0.35)',
        '2xl': '0 12px 24px rgba(0, 0, 0, 0.4)',
      },
      transitionDuration: {
        'fast': '100ms',
        'normal': '150ms',
      },
      transitionTimingFunction: {
        'out': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 100ms ease-out',
        'slide-up': 'slideUp 150ms ease-out',
        'scale-in': 'scaleIn 100ms ease-out',
        'pulse-recording': 'pulseRecording 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.97)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulseRecording: {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 0 0 rgba(248, 81, 73, 0.4)' },
          '50%': { opacity: '0.8', boxShadow: '0 0 0 8px rgba(248, 81, 73, 0)' },
        },
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}
