import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://farmers.okta.com/oauth2/v1/authorize?client_id=okta.2b1959c8-bcc0-56eb-a589-cfcfb7422f26&code_challenge=ISMPfb7Bnnk7YcPj39gcATsoNXOozPkAoV3BuG9ndjE&code_challenge_method=S256&nonce=fQb3ltjwNOCeGX4srzCUOjRWqRYQFbphiFeC7MYUiaaivARvtbiUPGrnL34d0Jai&redirect_uri=https%3A%2F%2Ffarmers.okta.com%2Fenduser%2Fcallback&response_type=code&state=KbuliJucAeAvCHVyzF1lr689Bp05uzaKDYGtEaqobWsDcZ5BhUS4DFEegsiQX1tZ&scope=openid%20profile%20email%20okta.users.read.self%20okta.users.manage.self%20okta.internal.enduser.read%20okta.internal.enduser.manage%20okta.enduser.dashboard.read%20okta.enduser.dashboard.manage%20okta.myAccount.sessions.manage%20okta.internal.navigation.enduser.read');
  await page.getByRole('textbox', { name: 'myID or Username' }).click();
  await page.getByRole('textbox', { name: 'myID or Username' }).fill('browbck_td');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Welcome@123Welcome@123');
  await page.getByRole('textbox', { name: 'Password' }).dblclick();
  await page.getByRole('textbox', { name: 'Password' }).fill('Welcome@123');
  await page.getByRole('button', { name: 'Verify' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'launch app APEX UAT' }).click();
  const page1 = await page1Promise;
  await page1.goto('https://farmersagent--fauat.sandbox.lightning.force.com/lightning/page/home');
  await page1.getByRole('link', { name: 'Accounts' }).click();
  await page1.getByRole('button', { name: 'New' }).click();
  await page1.locator('.slds-radio--faux').first().click();
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByRole('combobox', { name: 'Salutation' }).click();
  await page1.locator('span').filter({ hasText: 'Mr.' }).first().click();
  await page1.getByRole('textbox', { name: 'First Name', exact: true }).click();
  await page1.getByRole('textbox', { name: 'First Name', exact: true }).fill('Mike');
  await page1.getByRole('textbox', { name: 'Last Name' }).click();
  await page1.getByRole('textbox', { name: 'Last Name' }).fill('R');
  await page1.getByRole('combobox', { name: 'Source Category (PL)' }).click();
  await page1.getByRole('option', { name: 'Direct Contact' }).click();
  await page1.getByRole('combobox', { name: 'Current Lead Source (PL)' }).click();
  await page1.locator('span').filter({ hasText: 'Claimant' }).first().click();
  await page1.getByRole('combobox', { name: 'Residence Country' }).click();
  await page1.getByText('United States').click();
  await page1.getByRole('combobox', { name: 'Address Search' }).click();
  await page1.getByRole('combobox', { name: 'Address Search' }).click();
  await page1.getByRole('combobox', { name: 'Address Search' }).fill('1');
  await page1.getByRole('option', { name: '1100 Van Ness Avenue San' }).click();
  await page1.getByRole('button', { name: 'Save', exact: true }).click();
  await page1.goto('https://farmersagent--fauat.sandbox.lightning.force.com/lightning/r/Account/001D1000013uSgTIAU/view');
});