/**
 * Selector Services
 *
 * Provides robust selector extraction, Vero code generation,
 * fuzzy matching, and selector utilities for test recording.
 */

export {
  SELECTOR_EXTRACTOR_SCRIPT,
  injectSelectorExtractor,
  extractSelectorsFromElement,
  extractSelectorsFromPoint,
  type ExtractedSelectors,
} from './selectorExtractor';

export {
  buildVeroGenerationPrompt,
  generateVeroCodeSimple,
  type GeneratedVeroCode,
} from './VeroGenerator';

export {
  levenshteinDistance,
  calculateSimilarity,
  extractSelectorText,
  extractSelectorType,
  areSemanticallyRelated,
} from './selectorMatching';

export {
  parseSelectorValue,
  normalizeSelector,
  isAutoGenerated,
  buildCssSelector,
  toCamelCase,
  toPascalCase,
} from './selectorUtils';

export {
  generateSelector,
  generateFieldName,
} from './selectorGenerator';
