/**
 * Selector Generator - Generates Vero selectors and field names from element info
 *
 * Implements Playwright-style selector priority:
 * testId > role+name > label > placeholder > text > id > css
 *
 * Also generates camelCase field names from element attributes.
 */

import type { ElementInfo, SelectorResult } from '../pageObjectRegistry';
import { isAutoGenerated, buildCssSelector, toCamelCase } from './selectorUtils';

/**
 * Generate the best selector for an element (Playwright codegen style)
 */
export function generateSelector(element: ElementInfo): SelectorResult {
    // Priority order: testId > role+name > label > placeholder > text > id > css

    // 1. data-testid (highest priority)
    if (element.testId) {
        return {
            veroSelector: `testid "${element.testId}"`,
            selectorType: 'testid',
            confidence: 1.0,
            rawValue: element.testId
        };
    }

    // 2. Role with explicit accessible name (semantic)
    if (element.role && element.ariaLabel) {
        return {
            veroSelector: `role "${element.role}" name "${element.ariaLabel}"`,
            selectorType: 'role',
            confidence: 0.95,
            rawValue: `${element.role}:${element.ariaLabel}`
        };
    }

    // 2b. Role with visible text (except bare textbox role)
    if (element.role && element.role !== 'textbox' && element.text && element.text.length < 30) {
        return {
            veroSelector: `role "${element.role}" name "${element.text}"`,
            selectorType: 'role',
            confidence: 0.9,
            rawValue: `${element.role}:${element.text}`
        };
    }

    // 3. Label (for form elements)
    if (element.ariaLabel) {
        return {
            veroSelector: `label "${element.ariaLabel}"`,
            selectorType: 'label',
            confidence: 0.85,
            rawValue: element.ariaLabel
        };
    }

    // 4. Placeholder (for inputs)
    if (element.placeholder) {
        return {
            veroSelector: `placeholder "${element.placeholder}"`,
            selectorType: 'placeholder',
            confidence: 0.8,
            rawValue: element.placeholder
        };
    }

    // 5. Text content (for buttons, links, etc.)
    if (element.text && element.text.length < 30 && !isAutoGenerated(element.text)) {
        return {
            veroSelector: `text "${element.text}"`,
            selectorType: 'text',
            confidence: 0.7,
            rawValue: element.text
        };
    }

    // 6. ID (if not auto-generated)
    if (element.id && !isAutoGenerated(element.id)) {
        return {
            veroSelector: `#${element.id}`,
            selectorType: 'id',
            confidence: 0.6,
            rawValue: element.id
        };
    }

    // 7. Name attribute
    if (element.name) {
        return {
            veroSelector: `[name="${element.name}"]`,
            selectorType: 'css',
            confidence: 0.5,
            rawValue: element.name
        };
    }

    // 8. Fallback to CSS selector
    const cssSelector = buildCssSelector(element);
    return {
        veroSelector: cssSelector,
        selectorType: 'css',
        confidence: 0.3,
        rawValue: cssSelector
    };
}

/**
 * Generate a field name from element info
 */
export function generateFieldName(element: ElementInfo, action: string = 'click'): string {
    let baseName = '';

    if (element.testId) {
        baseName = element.testId;
    } else if (element.ariaLabel) {
        baseName = element.ariaLabel;
    } else if (element.placeholder) {
        baseName = element.placeholder;
    } else if (element.text && element.text.length < 20) {
        baseName = element.text;
    } else if (element.name) {
        baseName = element.name;
    } else if (element.id && !isAutoGenerated(element.id)) {
        baseName = element.id;
    } else {
        baseName = `${element.tagName}${action.charAt(0).toUpperCase() + action.slice(1)}`;
    }

    return toCamelCase(baseName);
}
