/**
 * Config Generator
 * Generates playwright.config.ts files
 */

import type { GenerateOptions } from '@playwright-web-app/shared';

/**
 * Generate Playwright configuration file
 */
export class ConfigGenerator {
    /**
     * Generate playwright.config.ts content
     */
    generate(options: GenerateOptions): string {
        const {
            baseUrl,
            timeout = 30000,
            retries = 0,
            browsers = ['chromium']
        } = options;

        const lines: string[] = [];

        // Imports
        lines.push(`import { defineConfig, devices } from '@playwright/test';`);
        lines.push('');

        // Config export
        lines.push(`/**`);
        lines.push(` * Playwright Test Configuration`);
        lines.push(` * Generated by Playwright Visual IDE`);
        lines.push(` * @see https://playwright.dev/docs/test-configuration`);
        lines.push(` */`);
        lines.push(`export default defineConfig({`);

        // Test directory
        lines.push(`  testDir: './tests',`);

        // Fully parallel
        lines.push(`  fullyParallel: true,`);

        // Fail the build on CI if you accidentally left test.only
        lines.push(`  forbidOnly: !!process.env.CI,`);

        // Retries
        lines.push(`  retries: process.env.CI ? 2 : ${retries},`);

        // Workers
        lines.push(`  workers: process.env.CI ? 1 : undefined,`);

        // Reporter
        lines.push(`  reporter: 'html',`);

        // Shared settings
        lines.push(`  use: {`);

        if (baseUrl) {
            lines.push(`    baseURL: '${baseUrl}',`);
        }

        lines.push(`    trace: 'on-first-retry',`);
        lines.push(`    screenshot: 'only-on-failure',`);
        lines.push(`  },`);

        // Timeout
        lines.push(`  timeout: ${timeout},`);

        // Projects (browsers)
        lines.push(`  projects: [`);

        if (browsers.includes('chromium')) {
            lines.push(`    {`);
            lines.push(`      name: 'chromium',`);
            lines.push(`      use: { ...devices['Desktop Chrome'] },`);
            lines.push(`    },`);
        }

        if (browsers.includes('firefox')) {
            lines.push(`    {`);
            lines.push(`      name: 'firefox',`);
            lines.push(`      use: { ...devices['Desktop Firefox'] },`);
            lines.push(`    },`);
        }

        if (browsers.includes('webkit')) {
            lines.push(`    {`);
            lines.push(`      name: 'webkit',`);
            lines.push(`      use: { ...devices['Desktop Safari'] },`);
            lines.push(`    },`);
        }

        // Mobile projects (optional, commented out)
        lines.push(`    /* Test against mobile viewports. */`);
        lines.push(`    // {`);
        lines.push(`    //   name: 'Mobile Chrome',`);
        lines.push(`    //   use: { ...devices['Pixel 5'] },`);
        lines.push(`    // },`);
        lines.push(`    // {`);
        lines.push(`    //   name: 'Mobile Safari',`);
        lines.push(`    //   use: { ...devices['iPhone 12'] },`);
        lines.push(`    // },`);

        lines.push(`  ],`);

        // Web server (optional, commented out)
        lines.push(`  /* Run your local dev server before starting the tests */`);
        lines.push(`  // webServer: {`);
        lines.push(`  //   command: 'npm run start',`);
        if (baseUrl) {
            lines.push(`  //   url: '${baseUrl}',`);
        }
        lines.push(`  //   reuseExistingServer: !process.env.CI,`);
        lines.push(`  // },`);

        lines.push(`});`);
        lines.push('');

        return lines.join('\n');
    }

    /**
     * Generate a minimal config (for simple use cases)
     */
    generateMinimal(options: GenerateOptions): string {
        const { baseUrl, timeout = 30000 } = options;

        return `import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: ${timeout},
  use: {
    ${baseUrl ? `baseURL: '${baseUrl}',\n    ` : ''}trace: 'on-first-retry',
  },
});
`;
    }
}
